package matchers

import (
	"strings"
	"testing"
	"time"
)

// Test fixtures: small dataset for testing all matchers
var (
	// Tenant salt for deterministic synthetic IDs in tests
	testSalt = []byte("test-tenant-salt-12345")

	// Synthetic IDs (would be generated by crypto.SyntheticID in real code)
	synUser1    = "syn_user_a1b2c3d4e5f6"
	synUser2    = "syn_user_f6e5d4c3b2a1"
	synCust1    = "syn_cust_123456789abc"
	synCust2    = "syn_cust_abc987654321"
	synSub1     = "syn_sub_sub1111111111"
	synSub2     = "syn_sub_sub2222222222"
	synInv1     = "syn_inv_inv1111111111"
	synInv2     = "syn_inv_inv2222222222"
	synPrice1   = "syn_price_p11111111"
	synPrice2   = "syn_price_p22222222"
	synProduct1 = "syn_prod_prod111111"
	synProduct2 = "syn_prod_prod222222"

	// Base timestamp: 2024-01-01 00:00:00 UTC
	baseTime = time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC).Unix()
)

// buildTestData creates a small, complete dataset for testing.
// Scenario:
// - User1 (syn_user_a1b2c3d4e5f6) has subscription1 with price1 and product1
// - User2 (syn_user_f6e5d4c3b2a1) has subscription2 with price2 and product2
// - Usage events:
//   1. User1 uses SKU=price1 at baseTime (exact deterministic match)
//   2. User1 uses SKU=price1 at baseTime+300s (temporal match with sub1 creation)
//   3. User2 uses SKU=price2 at baseTime+7200s (no temporal match, only SKU overlap)
//   4. User1 uses unknown SKU at baseTime+10000s (no SKU match)
//   5. User2 uses SKU=price1 at baseTime (SKU mismatch with user2's subscription)
func buildTestData() ([]UsageEvent, []SubscriptionLite, []InvoiceLite) {
	usages := []UsageEvent{
		{
			User:    synUser1,
			Feature: "export_csv",
			SKU:     synPrice1,
			At:      baseTime,
		},
		{
			User:    synUser1,
			Feature: "api_call",
			SKU:     synPrice1,
			At:      baseTime + 300, // 5 minutes after sub creation
		},
		{
			User:    synUser2,
			Feature: "export_csv",
			SKU:     synPrice2,
			At:      baseTime + 7200, // 2 hours after sub creation (outside temporal window)
		},
		{
			User:    synUser1,
			Feature: "unknown_feature",
			SKU:     "syn_price_unknown",
			At:      baseTime + 10000,
		},
		{
			User:    synUser2,
			Feature: "api_call",
			SKU:     synPrice1, // User2 using User1's SKU (cross-contamination test)
			At:      baseTime,
		},
	}

	subs := []SubscriptionLite{
		{
			ID:         synSub1,
			Customer:   synCust1, // Maps to synUser1 via deterministic matcher
			PriceIDs:   []string{synPrice1},
			ProductIDs: []string{synProduct1},
			CreatedAt:  baseTime,
			Status:     "active",
		},
		{
			ID:         synSub2,
			Customer:   synCust2, // Maps to synUser2
			PriceIDs:   []string{synPrice2},
			ProductIDs: []string{synProduct2},
			CreatedAt:  baseTime,
			Status:     "active",
		},
	}

	invs := []InvoiceLite{
		{
			ID:           synInv1,
			Customer:     synCust1,
			Subscription: synSub1,
			Total:        5000,
			Currency:     "usd",
			Status:       "paid",
			CreatedAt:    baseTime,
			Paid:         true,
		},
		{
			ID:           synInv2,
			Customer:     synCust2,
			Subscription: synSub2,
			Total:        10000,
			Currency:     "usd",
			Status:       "paid",
			CreatedAt:    baseTime,
			Paid:         true,
		},
	}

	return usages, subs, invs
}

// TestDeterministicMatcher_ExactMatches tests the deterministic ID matcher.
// Expects confidence = 1.0 for exact customer ID matches.
func TestDeterministicMatcher_ExactMatches(t *testing.T) {
	usages, subs, invs := buildTestData()

	// Override User IDs to match Customer IDs for deterministic matching
	usages[0].User = synCust1 // User1 -> Customer1
	usages[1].User = synCust1
	usages[2].User = synCust2 // User2 -> Customer2

	matcher := DeterministicIDMatcher{TenantSalt: testSalt}
	edges, err := matcher.Match(usages, subs, invs)
	if err != nil {
		t.Fatalf("DeterministicMatcher failed: %v", err)
	}

	// Expect at least 2 user->subscription edges (one per user)
	// Plus user->price and user->invoice edges
	if len(edges) < 2 {
		t.Errorf("expected at least 2 edges, got %d", len(edges))
	}

	// Check that all edges have confidence 1.0
	for i, edge := range edges {
		if edge.Confidence != 1.0 {
			t.Errorf("edge[%d]: expected confidence 1.0, got %.2f", i, edge.Confidence)
		}
		if edge.Proof == "" {
			t.Errorf("edge[%d]: proof is empty", i)
		}
		if !strings.HasPrefix(edge.From, "syn_") {
			t.Errorf("edge[%d]: From ID is not synthetic: %s", i, edge.From)
		}
		if !strings.HasPrefix(edge.To, "syn_") {
			t.Errorf("edge[%d]: To ID is not synthetic: %s", i, edge.To)
		}
	}

	// Check that proofs are deterministic (same inputs -> same proof)
	edges2, _ := matcher.Match(usages, subs, invs)
	if len(edges) != len(edges2) {
		t.Errorf("non-deterministic edge count: %d vs %d", len(edges), len(edges2))
	}
	for i := range edges {
		if edges[i].Proof != edges2[i].Proof {
			t.Errorf("edge[%d]: non-deterministic proof", i)
		}
	}
}

// TestTemporalMatcher_TimeWindow tests the temporal proximity matcher.
// Expects confidence in range (0, 0.6] based on time proximity.
func TestTemporalMatcher_TimeWindow(t *testing.T) {
	usages, subs, invs := buildTestData()

	// Use 1-hour (3600s) window
	matcher := TemporalMatcher{
		WindowSec:  3600,
		TenantSalt: testSalt,
	}

	edges, err := matcher.Match(usages, subs, invs)
	if err != nil {
		t.Fatalf("TemporalMatcher failed: %v", err)
	}

	// Expect matches for usage events within ±3600s of sub/inv creation
	// usages[0]: at baseTime (exact match with sub1/inv1 creation) -> confidence ~0.6
	// usages[1]: at baseTime+300 (5min after) -> confidence ~0.55
	// usages[2]: at baseTime+7200 (2h after) -> NO MATCH (outside window)

	if len(edges) == 0 {
		t.Fatal("expected at least 1 temporal edge")
	}

	for i, edge := range edges {
		// Check confidence range
		if edge.Confidence <= 0 || edge.Confidence > 0.6 {
			t.Errorf("edge[%d]: confidence out of range (0, 0.6]: %.2f", i, edge.Confidence)
		}
		// Check proof
		if edge.Proof == "" {
			t.Errorf("edge[%d]: proof is empty", i)
		}
		// Check notes mention time window
		if !strings.Contains(edge.Notes, "within") {
			t.Errorf("edge[%d]: notes should mention time window, got: %s", i, edge.Notes)
		}
	}
}

// TestSKUOverlapMatcher_SKUMatches tests the SKU overlap matcher.
// Expects confidence 0.8-0.9 for SKU matches.
func TestSKUOverlapMatcher_SKUMatches(t *testing.T) {
	usages, subs, _ := buildTestData()

	matcher := SKUOverlapMatcher{TenantSalt: testSalt}
	edges, err := matcher.Match(usages, subs, nil)
	if err != nil {
		t.Fatalf("SKUOverlapMatcher failed: %v", err)
	}

	// Expect matches for:
	// - usages[0]: User1 + SKU=price1 -> sub1 (has price1)
	// - usages[1]: User1 + SKU=price1 -> sub1
	// - usages[2]: User2 + SKU=price2 -> sub2 (has price2)
	// - usages[4]: User2 + SKU=price1 -> sub1 (cross-user match)

	if len(edges) == 0 {
		t.Fatal("expected at least 1 SKU overlap edge")
	}

	for i, edge := range edges {
		// Check confidence range (0.8 for subscription, 0.9 for price/product)
		if edge.Confidence < 0.8 || edge.Confidence > 0.9 {
			t.Errorf("edge[%d]: confidence out of range [0.8, 0.9]: %.2f", i, edge.Confidence)
		}
		// Check proof
		if edge.Proof == "" {
			t.Errorf("edge[%d]: proof is empty", i)
		}
		// Check notes mention SKU
		if !strings.Contains(edge.Notes, "SKU") {
			t.Errorf("edge[%d]: notes should mention SKU, got: %s", i, edge.Notes)
		}
	}
}

// TestEnsemble_WeightedCombination tests the ensemble combiner.
// Expects proper weighted combination and threshold filtering.
func TestEnsemble_WeightedCombination(t *testing.T) {
	usages, subs, invs := buildTestData()

	// Override User IDs to match Customer IDs for deterministic matching
	usages[0].User = synCust1
	usages[1].User = synCust1
	usages[2].User = synCust2

	// Create recipe with weights
	recipe := Recipe{
		Name:    "test",
		Version: "v1",
		Weights: map[string]float64{
			"deterministic_id":    1.0, // Full weight
			"temporal_proximity":  0.5, // Half weight
			"sku_overlap":         0.8, // 0.8 weight
		},
		Threshold:         0.8, // Accept if combined score >= 0.8
		TemporalWindowSec: 3600,
		SKUOverlapMin:     0.5,
	}

	// Create matchers
	detMatcher := DeterministicIDMatcher{TenantSalt: testSalt}
	tempMatcher := TemporalMatcher{WindowSec: 3600, TenantSalt: testSalt}
	skuMatcher := SKUOverlapMatcher{TenantSalt: testSalt}

	// Create ensemble
	ensemble := Ensemble{
		Recipe:     recipe,
		Matchers:   []Matcher{detMatcher, tempMatcher, skuMatcher},
		TenantSalt: testSalt,
	}

	// Run ensemble
	accepted, err := ensemble.RunEnsemble(usages, subs, invs)
	if err != nil {
		t.Fatalf("Ensemble failed: %v", err)
	}

	if len(accepted) == 0 {
		t.Fatal("expected at least 1 accepted edge")
	}

	// Check all accepted edges
	for i, edge := range accepted {
		// Check confidence is capped at 1.0
		if edge.Confidence > 1.0 {
			t.Errorf("edge[%d]: confidence exceeds 1.0: %.2f", i, edge.Confidence)
		}
		// Check confidence meets threshold
		if edge.Confidence < recipe.Threshold {
			t.Errorf("edge[%d]: confidence below threshold: %.2f < %.2f", i, edge.Confidence, recipe.Threshold)
		}
		// Check proof is present
		if edge.Proof == "" {
			t.Errorf("edge[%d]: proof is empty", i)
		}
		// Check recipe is set
		if edge.Recipe != "test/v1" {
			t.Errorf("edge[%d]: expected recipe 'test/v1', got '%s'", i, edge.Recipe)
		}
		// Check notes mention score
		if !strings.Contains(edge.Notes, "score=") {
			t.Errorf("edge[%d]: notes should mention combined score, got: %s", i, edge.Notes)
		}
	}
}

// TestEnsemble_ThresholdFiltering tests that ensemble correctly filters by threshold.
func TestEnsemble_ThresholdFiltering(t *testing.T) {
	usages, subs, invs := buildTestData()

	// Create recipe with HIGH threshold (1.5) - should reject most edges
	recipe := Recipe{
		Name:    "strict",
		Version: "v1",
		Weights: map[string]float64{
			"temporal_proximity": 0.5, // Only temporal matcher (max 0.6 confidence)
		},
		Threshold:         1.5, // Impossible to reach with single matcher
		TemporalWindowSec: 3600,
	}

	tempMatcher := TemporalMatcher{WindowSec: 3600, TenantSalt: testSalt}

	ensemble := Ensemble{
		Recipe:     recipe,
		Matchers:   []Matcher{tempMatcher},
		TenantSalt: testSalt,
	}

	accepted, err := ensemble.RunEnsemble(usages, subs, invs)
	if err != nil {
		t.Fatalf("Ensemble failed: %v", err)
	}

	// Expect 0 accepted edges (threshold too high)
	if len(accepted) != 0 {
		t.Errorf("expected 0 accepted edges (threshold too high), got %d", len(accepted))
	}
}

// TestRecipe_Validate tests recipe validation logic.
func TestRecipe_Validate(t *testing.T) {
	tests := []struct {
		name    string
		recipe  Recipe
		wantErr bool
	}{
		{
			name: "valid recipe",
			recipe: Recipe{
				Name:              "test",
				Version:           "v1",
				Threshold:         0.8,
				TemporalWindowSec: 3600,
				SKUOverlapMin:     0.5,
			},
			wantErr: false,
		},
		{
			name: "empty name",
			recipe: Recipe{
				Name:      "",
				Version:   "v1",
				Threshold: 0.8,
			},
			wantErr: true,
		},
		{
			name: "empty version",
			recipe: Recipe{
				Name:      "test",
				Version:   "",
				Threshold: 0.8,
			},
			wantErr: true,
		},
		{
			name: "threshold too high",
			recipe: Recipe{
				Name:      "test",
				Version:   "v1",
				Threshold: 1.5,
			},
			wantErr: true,
		},
		{
			name: "threshold negative",
			recipe: Recipe{
				Name:      "test",
				Version:   "v1",
				Threshold: -0.1,
			},
			wantErr: true,
		},
		{
			name: "temporal window negative",
			recipe: Recipe{
				Name:              "test",
				Version:           "v1",
				Threshold:         0.8,
				TemporalWindowSec: -100,
			},
			wantErr: true,
		},
		{
			name: "SKU overlap min too high",
			recipe: Recipe{
				Name:          "test",
				Version:       "v1",
				Threshold:     0.8,
				SKUOverlapMin: 1.5,
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.recipe.Validate()
			if (err != nil) != tt.wantErr {
				t.Errorf("Validate() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

// TestWithin tests the temporal proximity utility function.
func TestWithin(t *testing.T) {
	tests := []struct {
		name      string
		ts        int64
		center    int64
		windowSec int64
		want      bool
	}{
		{"exact match", 1000, 1000, 60, true},
		{"within window (before)", 970, 1000, 60, true},
		{"within window (after)", 1030, 1000, 60, true},
		{"outside window (before)", 900, 1000, 60, false},
		{"outside window (after)", 1100, 1000, 60, false},
		{"at boundary (before)", 940, 1000, 60, true},
		{"at boundary (after)", 1060, 1000, 60, true},
		{"zero window", 1000, 1000, 0, false},
		{"negative window", 1000, 1000, -10, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := Within(tt.ts, tt.center, tt.windowSec)
			if got != tt.want {
				t.Errorf("Within(%d, %d, %d) = %v, want %v",
					tt.ts, tt.center, tt.windowSec, got, tt.want)
			}
		})
	}
}

// TestNoRawIDs_Privacy verifies that no raw (non-synthetic) IDs appear in edges.
// This is a critical privacy test.
func TestNoRawIDs_Privacy(t *testing.T) {
	usages, subs, invs := buildTestData()

	// Override User IDs to match Customer IDs
	usages[0].User = synCust1
	usages[1].User = synCust1

	// Create ensemble with all matchers
	recipe := Recipe{
		Name:    "privacy_test",
		Version: "v1",
		Weights: map[string]float64{
			"deterministic_id":   1.0,
			"temporal_proximity": 0.5,
			"sku_overlap":        0.8,
		},
		Threshold:         0.5,
		TemporalWindowSec: 3600,
	}

	ensemble := Ensemble{
		Recipe: recipe,
		Matchers: []Matcher{
			DeterministicIDMatcher{TenantSalt: testSalt},
			TemporalMatcher{WindowSec: 3600, TenantSalt: testSalt},
			SKUOverlapMatcher{TenantSalt: testSalt},
		},
		TenantSalt: testSalt,
	}

	accepted, err := ensemble.RunEnsemble(usages, subs, invs)
	if err != nil {
		t.Fatalf("Ensemble failed: %v", err)
	}

	// Check all edges for privacy compliance
	for i, edge := range accepted {
		// From and To must be synthetic
		if !strings.HasPrefix(edge.From, "syn_") {
			t.Errorf("edge[%d]: From ID is not synthetic: %s", i, edge.From)
		}
		if !strings.HasPrefix(edge.To, "syn_") {
			t.Errorf("edge[%d]: To ID is not synthetic: %s", i, edge.To)
		}

		// Notes should not contain raw Stripe IDs (no "cus_", "sub_", "in_", "price_", "prod_")
		if strings.Contains(edge.Notes, "cus_") || strings.Contains(edge.Notes, "sub_") ||
			strings.Contains(edge.Notes, "in_") || strings.Contains(edge.Notes, "price_") ||
			strings.Contains(edge.Notes, "prod_") {
			t.Errorf("edge[%d]: Notes contain raw Stripe ID patterns: %s", i, edge.Notes)
		}

		// Proof should be a hex string (HMAC-SHA256)
		if len(edge.Proof) != 64 {
			t.Errorf("edge[%d]: Proof should be 64-char hex string, got %d chars", i, len(edge.Proof))
		}
	}
}

// BenchmarkDeterministicMatcher benchmarks the deterministic matcher.
func BenchmarkDeterministicMatcher(b *testing.B) {
	usages, subs, invs := buildTestData()
	matcher := DeterministicIDMatcher{TenantSalt: testSalt}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := matcher.Match(usages, subs, invs)
		if err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkTemporalMatcher benchmarks the temporal matcher.
func BenchmarkTemporalMatcher(b *testing.B) {
	usages, subs, invs := buildTestData()
	matcher := TemporalMatcher{WindowSec: 3600, TenantSalt: testSalt}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := matcher.Match(usages, subs, invs)
		if err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkSKUOverlapMatcher benchmarks the SKU overlap matcher.
func BenchmarkSKUOverlapMatcher(b *testing.B) {
	usages, subs, _ := buildTestData()
	matcher := SKUOverlapMatcher{TenantSalt: testSalt}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := matcher.Match(usages, subs, nil)
		if err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkEnsemble benchmarks the full ensemble pipeline.
func BenchmarkEnsemble(b *testing.B) {
	usages, subs, invs := buildTestData()

	recipe := Recipe{
		Name:    "bench",
		Version: "v1",
		Weights: map[string]float64{
			"deterministic_id":   1.0,
			"temporal_proximity": 0.5,
			"sku_overlap":        0.8,
		},
		Threshold:         0.8,
		TemporalWindowSec: 3600,
	}

	ensemble := Ensemble{
		Recipe: recipe,
		Matchers: []Matcher{
			DeterministicIDMatcher{TenantSalt: testSalt},
			TemporalMatcher{WindowSec: 3600, TenantSalt: testSalt},
			SKUOverlapMatcher{TenantSalt: testSalt},
		},
		TenantSalt: testSalt,
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := ensemble.RunEnsemble(usages, subs, invs)
		if err != nil {
			b.Fatal(err)
		}
	}
}
