{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connektn-agent.fullname" . }}
  labels:
    {{- include "connektn-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  STRIPE_API_KEY: {{ .Values.secrets.stripeApiKey | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripeWebhookSecret | quote }}
  TENANT_SALT: {{ .Values.secrets.tenantSalt | quote }}
  ORGANIZATION_ID: {{ .Values.secrets.organizationId | quote }}
  {{- if .Values.config.heartbeat.enabled }}
  HEARTBEAT_SECRET: {{ .Values.secrets.heartbeatSecret | quote }}
  {{- end }}
  {{- if .Values.config.control.enabled }}
  CONTROL_SECRET: {{ .Values.secrets.controlSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.connektnTenantKey }}
  CONNEKTN_TENANT_KEY: {{ .Values.secrets.connektnTenantKey | quote }}
  {{- end }}
  {{- if eq .Values.queue.type "kafka" }}
  {{- if .Values.queue.kafka.sasl.enabled }}
  KAFKA_SASL_USERNAME: {{ .Values.queue.kafka.sasl.username | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.queue.kafka.sasl.password | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.queue.type "rabbitmq" }}
  RABBITMQ_USERNAME: {{ .Values.queue.rabbitmq.auth.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.queue.rabbitmq.auth.password | quote }}
  {{- end }}
{{- end }}
